# Generated by Django 5.1.2 on 2024-10-25 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
        ('gestion_stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='employe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='employes.employe'),
        ),
    ]
