# Generated by Django 5.1.2 on 2024-10-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_remove_groupepermission_roles_remove_employe_groupes_and_more'),
        ('gestion_stocks', '0002_sale_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='employe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='employes.employe'),
        ),
    ]
