# Generated by Django 5.1.2 on 2024-10-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupepermission',
            name='roles',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='groupes',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='employe',
            name='role',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='CaisseEmploye',
        ),
        migrations.DeleteModel(
            name='GroupePermission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
